const pptxgen = require("pptxgenjs");
const fs = require("fs");
const args = process.argv.slice(2);
const jsonPath = args[0] || "output/_ppt_data.json";
const outPath = args[1] || "output/컨설팅보고서_최종.pptx";
const raw = fs.readFileSync(jsonPath, "utf8");
const DATA = JSON.parse(raw);
const C = { navy:"000080", white:"FFFFFF", gray:"D1D9E6", grayLight:"F4F6FA", grayMid:"888888", grayDark:"333333", ice:"EEF2FF", critical:"7F1D1D", high:"78350F", medium:"475569", low:"94A3B8" };
const pres = new pptxgen();
pres.layout = "LAYOUT_16x9";
const ms = () => ({ type:"outer", blur:6, offset:2, angle:135, color:"000000", opacity:0.08 });
function rc(l){ const u=(l||"").toUpperCase(); if(u.includes("CRITICAL"))return C.critical; if(u.includes("HIGH"))return C.high; if(u.includes("MEDIUM"))return C.medium; return C.low; }
function rbg(l){ const u=(l||"").toUpperCase(); if(u.includes("CRITICAL"))return "FEF2F2"; if(u.includes("HIGH"))return "FFFBEB"; if(u.includes("MEDIUM"))return "F8FAFC"; return "F4F6FA"; }
function hdr(s,t,n){ s.background={color:C.white}; s.addShape(pres.shapes.RECTANGLE,{x:0,y:0,w:10,h:0.65,fill:{color:C.navy},line:{color:C.navy}}); s.addShape(pres.shapes.RECTANGLE,{x:0,y:0.65,w:10,h:0.04,fill:{color:C.gray},line:{color:C.gray}}); s.addText(t,{x:0.4,y:0,w:8,h:0.65,fontSize:18,fontFace:"나눔고딕",color:C.white,bold:true,valign:"middle",margin:0}); if(n)s.addText(`${n}/6`,{x:8.5,y:0,w:1.3,h:0.65,fontSize:10,fontFace:"Calibri",color:C.gray,align:"right",valign:"middle",margin:0}); }
function ftr(s,c){ s.addShape(pres.shapes.RECTANGLE,{x:0,y:5.45,w:10,h:0.175,fill:{color:C.grayLight},line:{color:C.gray,width:0.3}}); s.addText(c,{x:0.3,y:5.45,w:4,h:0.175,fontSize:9,fontFace:"나눔고딕",color:C.grayMid,valign:"middle",margin:0}); s.addText("본 보고서는 AI 에이전트 분석 결과입니다. 최종 의사결정 전 전문가 검토를 권고합니다.",{x:3.5,y:5.45,w:6.2,h:0.175,fontSize:8.5,fontFace:"나눔고딕",color:C.grayMid,align:"right",valign:"middle",margin:0}); }
// S1 표지
{ const s=pres.addSlide(); s.background={color:C.white}; s.addShape(pres.shapes.RECTANGLE,{x:0,y:0,w:0.22,h:5.625,fill:{color:C.navy},line:{color:C.navy}}); s.addShape(pres.shapes.RECTANGLE,{x:0.22,y:0,w:9.78,h:2.6,fill:{color:C.navy},line:{color:C.navy}}); s.addText("중소기업 경영컨설팅",{x:0.55,y:0.35,w:9,h:0.5,fontSize:15,fontFace:"나눔고딕",color:C.gray,margin:0}); s.addText("종합 분석 보고서",{x:0.55,y:0.82,w:9,h:1.1,fontSize:42,fontFace:"나눔고딕",color:C.white,bold:true,margin:0}); s.addShape(pres.shapes.RECTANGLE,{x:0.55,y:2.1,w:4,h:0.05,fill:{color:C.gray},line:{color:C.gray}}); s.addText(DATA.company,{x:0.55,y:2.8,w:9,h:0.9,fontSize:34,fontFace:"나눔고딕",color:C.navy,bold:true,margin:0}); s.addShape(pres.shapes.RECTANGLE,{x:0.55,y:3.78,w:9.2,h:0.03,fill:{color:C.gray},line:{color:C.gray}}); [["23개","분석 에이전트","5개 그룹"],["14개","분석 도메인","전문 영역"],[DATA.date,"보고서 생성일",""]].forEach((k,i)=>{ const x=0.55+i*3.1; s.addText(k[0],{x,y:3.95,w:2.9,h:0.55,fontSize:22,fontFace:"Calibri",color:C.navy,bold:true,margin:0}); s.addText(k[1],{x,y:4.5,w:2.9,h:0.3,fontSize:11,fontFace:"나눔고딕",color:C.grayMid,margin:0}); }); s.addText("본 보고서는 AI 에이전트 분석 결과이며, 최종 의사결정 전 전문가 검토를 권고합니다.",{x:0.55,y:5.1,w:9,h:0.3,fontSize:9,fontFace:"나눔고딕",color:C.grayMid,margin:0}); }
// S2 Executive Summary
{ const s=pres.addSlide(); hdr(s,"Executive Summary — 경영 현황 종합 진단","2"); const pc=DATA.판정==="RED"?C.critical:DATA.판정==="YELLOW"?C.medium:C.low; s.addShape(pres.shapes.RECTANGLE,{x:0.3,y:0.82,w:2.0,h:0.95,fill:{color:pc},line:{color:pc},shadow:ms()}); s.addText("종합 판정",{x:0.3,y:0.85,w:2.0,h:0.28,fontSize:10,fontFace:"나눔고딕",color:"FFFFFF",align:"center",margin:0}); s.addText(DATA.판정,{x:0.3,y:1.12,w:2.0,h:0.58,fontSize:32,fontFace:"Calibri",color:"FFFFFF",bold:true,align:"center",margin:0}); const tx=2.55,tw=7.15; s.addShape(pres.shapes.RECTANGLE,{x:tx,y:0.82,w:tw,h:0.38,fill:{color:C.navy},line:{color:C.navy}}); s.addText("진단 영역",{x:tx+0.1,y:0.82,w:2.5,h:0.38,fontSize:11,fontFace:"나눔고딕",color:C.white,bold:true,valign:"middle",margin:0}); s.addText("위험등급",{x:tx+2.6,y:0.82,w:1.3,h:0.38,fontSize:11,fontFace:"나눔고딕",color:C.white,bold:true,align:"center",valign:"middle",margin:0}); s.addText("핵심 지표",{x:tx+3.95,y:0.82,w:3.1,h:0.38,fontSize:11,fontFace:"나눔고딕",color:C.white,bold:true,valign:"middle",margin:0}); DATA.진단.forEach((d,i)=>{ const y=1.2+i*0.67; s.addShape(pres.shapes.RECTANGLE,{x:tx,y,w:tw,h:0.62,fill:{color:rbg(d.등급)},line:{color:C.gray,width:0.3}}); s.addText(d.영역,{x:tx+0.1,y,w:2.5,h:0.62,fontSize:11,fontFace:"나눔고딕",color:C.navy,bold:true,valign:"middle",margin:0}); s.addShape(pres.shapes.RECTANGLE,{x:tx+2.65,y:y+0.14,w:1.2,h:0.35,fill:{color:rc(d.등급)},line:{color:rc(d.등급)}}); s.addText(d.등급,{x:tx+2.65,y:y+0.14,w:1.2,h:0.35,fontSize:9.5,fontFace:"Calibri",color:C.white,bold:true,align:"center",valign:"middle",margin:0}); s.addText(d.지표,{x:tx+3.95,y,w:3.1,h:0.62,fontSize:9.5,fontFace:"나눔고딕",color:C.grayDark,valign:"middle",margin:0}); }); ftr(s,DATA.company); }
// S3 TOP5
{ const s=pres.addSlide(); hdr(s,"즉시 실행 과제  TOP 5","3"); DATA.top5.forEach((t,i)=>{ const y=0.78+i*0.92; s.addShape(pres.shapes.RECTANGLE,{x:0.3,y,w:9.4,h:0.85,fill:{color:rbg(t.등급)},line:{color:C.gray,width:0.3},shadow:ms()}); s.addShape(pres.shapes.RECTANGLE,{x:0.3,y,w:0.55,h:0.85,fill:{color:C.navy},line:{color:C.navy}}); s.addText(t.no,{x:0.3,y,w:0.55,h:0.85,fontSize:14,fontFace:"Calibri",color:C.white,bold:true,align:"center",valign:"middle",margin:0}); s.addShape(pres.shapes.RECTANGLE,{x:0.88,y:y+0.07,w:0.9,h:0.28,fill:{color:rc(t.등급)},line:{color:rc(t.등급)}}); s.addText(t.등급,{x:0.88,y:y+0.07,w:0.9,h:0.28,fontSize:8.5,fontFace:"Calibri",color:C.white,bold:true,align:"center",valign:"middle",margin:0}); s.addShape(pres.shapes.RECTANGLE,{x:0.88,y:y+0.42,w:0.9,h:0.24,fill:{color:C.grayLight},line:{color:C.gray,width:0.3}}); s.addText(t.기한,{x:0.88,y:y+0.42,w:0.9,h:0.24,fontSize:8.5,fontFace:"Calibri",color:C.navy,bold:true,align:"center",valign:"middle",margin:0}); s.addText(t.제목,{x:1.85,y:y+0.05,w:7.7,h:0.3,fontSize:12,fontFace:"나눔고딕",color:C.navy,bold:true,margin:0}); s.addText("— "+(t.items[0]||""),{x:1.85,y:y+0.38,w:7.7,h:0.4,fontSize:9.5,fontFace:"나눔고딕",color:C.grayDark,margin:0}); }); ftr(s,DATA.company); }
// S4 절세효과
{ const s=pres.addSlide(); hdr(s,"예상 절세·절감 효과","4"); [["연간 총 절세·절감","1.7 ~ 2.2억원","직접 절세 + 금융비용 절감"],["7년 누적 효과","12 ~ 15억원","복리 효과 미포함"]].forEach((k,i)=>{ const x=0.3+i*4.85; s.addShape(pres.shapes.RECTANGLE,{x,y:0.82,w:4.55,h:1.05,fill:{color:C.ice},line:{color:C.navy,width:0.8},shadow:ms()}); s.addShape(pres.shapes.RECTANGLE,{x,y:0.82,w:4.55,h:0.06,fill:{color:C.navy},line:{color:C.navy}}); s.addText(k[0],{x,y:0.95,w:4.55,h:0.28,fontSize:11,fontFace:"나눔고딕",color:C.grayMid,align:"center",margin:0}); s.addText(k[1],{x,y:1.2,w:4.55,h:0.45,fontSize:26,fontFace:"Calibri",color:C.navy,bold:true,align:"center",margin:0}); s.addText(k[2],{x,y:1.65,w:4.55,h:0.2,fontSize:9.5,fontFace:"나눔고딕",color:C.grayMid,align:"center",margin:0}); }); s.addShape(pres.shapes.RECTANGLE,{x:0.3,y:2.08,w:9.4,h:0.38,fill:{color:C.navy},line:{color:C.navy}}); s.addText("절세·절감 항목",{x:0.4,y:2.08,w:5.4,h:0.38,fontSize:11,fontFace:"나눔고딕",color:C.white,bold:true,valign:"middle",margin:0}); s.addText("연간 효과",{x:5.85,y:2.08,w:2.0,h:0.38,fontSize:11,fontFace:"나눔고딕",color:C.white,bold:true,align:"center",valign:"middle",margin:0}); s.addText("비고",{x:7.9,y:2.08,w:1.7,h:0.38,fontSize:11,fontFace:"나눔고딕",color:C.white,bold:true,align:"center",valign:"middle",margin:0}); DATA.절세.forEach((r,i)=>{ const y=2.46+i*0.68; s.addShape(pres.shapes.RECTANGLE,{x:0.3,y,w:9.4,h:0.62,fill:{color:i%2===0?C.white:C.grayLight},line:{color:C.gray,width:0.3}}); s.addShape(pres.shapes.RECTANGLE,{x:0.3,y:y+0.15,w:0.06,h:0.32,fill:{color:C.navy},line:{color:C.navy}}); s.addText(r.항목,{x:0.45,y,w:5.35,h:0.62,fontSize:11,fontFace:"나눔고딕",color:C.grayDark,valign:"middle",margin:0}); s.addText(r.연간,{x:5.85,y,w:2.0,h:0.62,fontSize:12,fontFace:"Calibri",color:C.navy,bold:true,align:"center",valign:"middle",margin:0}); s.addText(r.비고,{x:7.9,y,w:1.7,h:0.62,fontSize:10,fontFace:"나눔고딕",color:C.grayMid,align:"center",valign:"middle",margin:0}); }); ftr(s,DATA.company); }
// S5 에이전트
{ const s=pres.addSlide(); hdr(s,"에이전트별 핵심 발견사항","5"); const col=[0.3,5.15]; DATA.에이전트.forEach((a,i)=>{ const x=col[i%2],y=0.82+Math.floor(i/2)*0.65,w=4.7,h=0.58; s.addShape(pres.shapes.RECTANGLE,{x,y,w,h,fill:{color:C.white},line:{color:C.gray,width:0.4},shadow:ms()}); s.addShape(pres.shapes.RECTANGLE,{x,y,w:0.08,h,fill:{color:C.navy},line:{color:C.navy}}); s.addText(a.명칭,{x:x+0.15,y:y+0.04,w:1.1,h:0.24,fontSize:10,fontFace:"나눔고딕",color:C.navy,bold:true,margin:0}); s.addText(a.핵심,{x:x+0.15,y:y+0.28,w:w-0.25,h:0.25,fontSize:9,fontFace:"나눔고딕",color:C.grayDark,margin:0}); }); ftr(s,DATA.company); }
// S6 중장기
{ const s=pres.addSlide(); hdr(s,"중장기 전략 방향","6"); [{title:"단기  3~6개월",color:C.critical,data:DATA.중장기.단기,x:0.3},{title:"중기  6~12개월",color:C.medium,data:DATA.중장기.중기,x:5.15}].forEach(col=>{ const w=4.65; s.addShape(pres.shapes.RECTANGLE,{x:col.x,y:0.82,w,h:0.42,fill:{color:col.color},line:{color:col.color}}); s.addText(col.title,{x:col.x+0.15,y:0.82,w,h:0.42,fontSize:13,fontFace:"나눔고딕",color:C.white,bold:true,valign:"middle",margin:0}); col.data.forEach((d,i)=>{ const y=1.35+i*1.0; s.addShape(pres.shapes.RECTANGLE,{x:col.x,y,w,h:0.9,fill:{color:i%2===0?C.white:C.grayLight},line:{color:C.gray,width:0.3},shadow:ms()}); s.addShape(pres.shapes.RECTANGLE,{x:col.x,y:y+0.1,w:0.06,h:0.7,fill:{color:col.color},line:{color:col.color}}); s.addText(d.과제,{x:col.x+0.18,y:y+0.06,w:w-0.25,h:0.26,fontSize:11,fontFace:"나눔고딕",color:C.navy,bold:true,margin:0}); s.addText("목표: "+d.목표,{x:col.x+0.18,y:y+0.32,w:w-0.25,h:0.22,fontSize:10,fontFace:"나눔고딕",color:col.color,margin:0}); s.addText(d.방법,{x:col.x+0.18,y:y+0.54,w:w-0.25,h:0.28,fontSize:9.5,fontFace:"나눔고딕",color:C.grayDark,margin:0}); }); }); ftr(s,DATA.company); }
pres.writeFile({fileName:outPath}).then(()=>console.log("✅ 완료:",outPath)).catch(e=>console.error("❌",e));
