"""
_generate_specs.py
ACTIVE 37개 에이전트 8항목 표준 명세서 자동 생성
실행: python agents/active/_generate_specs.py (consulting-agent/ 기준)
"""
import os

OUT = os.path.dirname(os.path.abspath(__file__))

# ──────────────────────────────────────────────────────────────
# 37개 에이전트 메타 정의 (orchestrator 분석 기준)
# ──────────────────────────────────────────────────────────────
AGENTS = [
  # ── GROUP A (4) ─────────────────────────────────────────────
  dict(
    name="TaxAgent", file="consulting_agents.py", group="A", step=1,
    model="claude-sonnet-4-6",
    role="법인세 절세 전략",
    single_resp="과세표준·가지급금 입력 → 법인세 절세 전략 3가지 + 가지급금 해결 방안 산출.",
    inputs_req="과세표준(taxable_income), 가지급금 잔액(provisional_payment), 기업개요(brief)",
    inputs_opt="업종, 임직원수, 특수관계인 거래 현황",
    outputs_fmt="Markdown 텍스트 (절세전략 3종 + 로드맵)",
    outputs_fields="절세전략명 / 예상절감액 / 적용세법 / 실행단계",
    tools="calc_corporate_tax() [내부 도구] / BaseAgent.run()",
    api="없음 (내부 계산)",
    verify_group="VerifyTax",
    law_ref="법인세법 §55 (2026 세율표: 10%/20%/22%/25%)",
    perspective_4="법인(손금극대화), 주주(가처분소득), 과세관청(적법성), 금융기관(재무구조영향)",
    upstream="DataValidationAgent (입력 정합성)", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 (_run_agent_safe) → agent_errors 기록",
    kpi_acc="90%+ (계산 오류 0건)", kpi_time="30~45초", kpi_token="4,000~6,000",
    correction_count=1,
  ),
  dict(
    name="StockAgent", file="consulting_agents.py", group="A", step=1,
    model="claude-sonnet-4-6",
    role="비상장주식 평가·이동",
    single_resp="1주당 순자산가치·순손익가치 입력 → 보충적 평가액 + 주식 이동·차명주식 해소 전략 산출.",
    inputs_req="순자산가치(net_asset_per_share), 순손익가치(net_income_per_share), 업력(years_in_operation), 부동산비율",
    inputs_opt="차명주식 수량, 취득연도",
    outputs_fmt="Markdown 텍스트 (평가액 계산표 + 이동 시나리오)",
    outputs_fields="평가액 / 가중치 근거 / 절세 이동 시나리오",
    tools="calc_unlisted_stock_value() [내부 도구] / BaseAgent.run()",
    api="없음",
    verify_group="VerifyTax",
    law_ref="상증세법 §54~56 (순손익3:순자산2 또는 부동산비율별 가중치)",
    perspective_4="법인(주식가치관리), 주주(지분가치보전), 과세관청(보충적평가 적법성), 금융기관(담보평가영향)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (상증세법 공식 계산)", kpi_time="30~45초", kpi_token="3,000~5,000",
    correction_count=1,
  ),
  dict(
    name="SuccessionAgent", file="consulting_agents.py", group="A", step=1,
    model="claude-sonnet-4-6",
    role="가업승계",
    single_resp="가업자산·업력·대표 나이 입력 → 가업상속공제 요건·한도 + 자녀법인 사전 승계 전략 산출.",
    inputs_req="업력(years_in_operation), 가업자산(business_value), 대표나이(ceo_age)",
    inputs_opt="자녀 나이·지분 현황, 사전 증여 이력",
    outputs_fmt="Markdown 텍스트 (시나리오별 공제 한도 + 실행 단계)",
    outputs_fields="공제한도 / 세부담비교 / 사전승계방안 / 사후관리의무",
    tools="calc_inheritance_deduction() [내부 도구] / BaseAgent.run()",
    api="없음",
    verify_group="VerifyTax",
    law_ref="상증세법 §18의2 (가업상속공제 최대 600억, 10/20/30년 차등)",
    perspective_4="법인(경영연속성), 주주(승계비용최소화), 과세관청(공제요건적법성), 금융기관(담보연속성)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="90%+", kpi_time="30~60초", kpi_token="4,000~6,000",
    correction_count=2,
  ),
  dict(
    name="FinanceAgent", file="consulting_agents.py", group="A", step=1,
    model="claude-sonnet-4-6",
    role="재무구조 개선·리스크헷지",
    single_resp="부채비율·유동비율 입력 → 재무구조 종합 진단 + 3단계 개선 로드맵 산출.",
    inputs_req="총부채(total_debt), 자기자본(total_equity), 유동자산(current_assets), 유동부채(current_liabilities)",
    inputs_opt="담보자산, 금융기관별 대출 현황",
    outputs_fmt="Markdown 텍스트 (진단등급 + 로드맵)",
    outputs_fields="부채비율 / 유동비율 / ROE / 개선방안 3단계",
    tools="analyze_financial_ratios() [내부 도구] / BaseAgent.run()",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="[보정필요: 특정 법령 없음, 재무지표 기준 적용]",
    perspective_4="법인(재무건전성), 주주(배당가능이익), 과세관청(과소자본세제), 금융기관(신용등급·담보가치)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="3,000~5,000",
    correction_count=2,
  ),
  # ── GROUP B (5) ─────────────────────────────────────────────
  dict(
    name="LegalAgent", file="legal_agent.py", group="B", step=1,
    model="claude-sonnet-4-6",
    role="법무 리스크 진단",
    single_resp="법인 운영 현황 입력 → 상법 절차 위반·특수관계인 거래 공정거래법·차명주식 형사 리스크 진단 및 해소 방안 산출.",
    inputs_req="기업개요(brief), 특수관계인 거래 현황, 명의신탁 여부",
    inputs_opt="이사회 의사록, 정관 내용",
    outputs_fmt="Markdown 텍스트 (리스크별 진단 + 해소 방안)",
    outputs_fields="리스크유형 / 위반여부 / 해소방안 / 우선순위",
    tools="BaseAgent.run()",
    api="없음",
    verify_group="VerifyOps",
    law_ref="상법 §382·§388 / 공정거래법 §45 / 금융실명법 §3 / 특정경제범죄법",
    perspective_4="법인(상법준수), 주주(형사리스크), 과세관청(세무조사연계), 금융기관(법적리스크영향)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="PatentAgent", file="patent_agent.py", group="B", step=1,
    model="claude-sonnet-4-6",
    role="R&D·특허 최적화",
    single_resp="R&D 지출·특허 수 입력 → R&D 세액공제 최적화 전략 + 기술보증기금 활용 + 특허권 법인 이전 방안 산출.",
    inputs_req="R&D 지출(rd_expense), 특허 수(patents), 업종(industry)",
    inputs_opt="연구개발비 명세, 기술등급",
    outputs_fmt="Markdown 텍스트 (공제액 계산 + 전략)",
    outputs_fields="공제율 / 공제금액 / 기술보증 조건 / 이전 세부담",
    tools="BaseAgent.run()",
    api="없음 (향후 특허청 API 연동 예정)",
    verify_group="VerifyOps",
    law_ref="조세특례제한법 §10 (R&D 세액공제), §12 (기술이전 과세특례)",
    perspective_4="법인(R&D손금극대화), 주주(특허이전절세), 과세관청(세액공제요건), 금융기관(기보보증가용성)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="LaborAgent", file="labor_agent.py", group="B", step=1,
    model="claude-sonnet-4-6",
    role="인사노무 진단",
    single_resp="임직원 수·업종 입력 → 통상임금 적정성·퇴직금 적립·4대보험 두루누리·중대재해법 대응 현황 진단.",
    inputs_req="임직원수(employees), 업종(industry), 연매출(revenue)",
    inputs_opt="임금명세서, 퇴직금 적립 현황",
    outputs_fmt="Markdown 텍스트 (항목별 진단 + 개선 방안)",
    outputs_fields="통상임금판단 / 퇴직금충당부족액 / 두루누리적용여부 / 중대재해법등급",
    tools="BaseAgent.run()",
    api="없음",
    verify_group="VerifyOps",
    law_ref="근로기준법 §2 / 근로자퇴직급여보장법 §4 / 중대재해처벌법 §4 / 고용보험법 §19",
    perspective_4="법인(노무리스크최소화), 주주(인건비최적화), 과세관청(원천징수적정성), 금융기관(인건비비율영향)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="RealEstateAgent", file="real_estate_agent.py", group="B", step=1,
    model="claude-sonnet-4-6",
    role="법인 부동산 전략",
    single_resp="부동산 자산 유형·가액 입력 → 법인 vs 개인 보유 세금 비교 + 공장 매각 최적화 + 임대차 리스크 분석.",
    inputs_req="부동산가액(real_estate.value), 부동산유형(real_estate.type)",
    inputs_opt="취득가액, 보유기간, 임대차계약 현황",
    outputs_fmt="Markdown 텍스트 (법인vs개인 세부담 비교표 + 전략)",
    outputs_fields="법인세부담 / 개인세부담 / 매각타이밍 / 임대차리스크",
    tools="BaseAgent.run()",
    api="없음 (향후 공시지가 API 연동 예정)",
    verify_group="VerifyOps",
    law_ref="법인세법 §55 / 소득세법 §104 (양도소득세) / 지방세법 §7 (취득세)",
    perspective_4="법인(부동산과다법인회피), 주주(매각차익최적화), 과세관청(양도세·취득세), 금융기관(담보평가변동)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="InsuranceAgent", file="insurance_agent.py", group="B", step=1,
    model="claude-sonnet-4-6",
    role="보험·리스크 헷지",
    single_resp="대표이사 나이·승계 계획 입력 → CEO 유고 리스크 헷지 + 임원 퇴직금 재원 보험 설계 + D&O 보험 진단.",
    inputs_req="대표이사나이(ceo_age), 연매출(revenue), 총자산(total_assets)",
    inputs_opt="현재 보험 가입 현황, 임원 수",
    outputs_fmt="Markdown 텍스트 (리스크별 보험 설계안)",
    outputs_fields="보험유형 / 보장금액 / 손금처리여부 / 우선순위",
    tools="BaseAgent.run()",
    api="없음",
    verify_group="VerifyOps",
    law_ref="법인세법 §24 (보험료 손금), 보험업법",
    perspective_4="법인(CEO리스크헷지), 주주(상속재원마련), 과세관청(보험료손금인정), 금융기관(신용보강효과)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  # ── GROUP C (7) ─────────────────────────────────────────────
  dict(
    name="IndustryAgent", file="industry_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="업종 벤치마크·세무조사 트렌드",
    single_resp="업종·매출·임직원 입력 → 동종업계 재무 벤치마크(부채비율·영업이익률·ROE) + 최근 세무조사 트렌드 분석.",
    inputs_req="업종(industry), 매출(revenue), 임직원수(employees)",
    inputs_opt="KSIC 코드, 지역",
    outputs_fmt="Markdown 텍스트 (벤치마크 표 + 세무조사 트렌드)",
    outputs_fields="업종평균비교표 / 취약지표 / 세무조사우선항목",
    tools="BaseAgent.run()",
    api="[보정필요: DART_API 연동 여부 확인]",
    verify_group="VerifyStrategy",
    law_ref="[보정필요: 벤치마크 출처 명시 필요]",
    perspective_4="법인(업종리스크파악), 주주(비교우위분석), 과세관청(세무조사트렌드), 금융기관(업종신용도)",
    upstream="없음 (독립 실행)", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="WebResearchAgent", file="web_research_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="웹 리서치",
    single_resp="기업명·업종·주요 고객사 입력 → 최신 업계 동향 + 특허청 정보 + 공급망 요건 조사.",
    inputs_req="기업명(company_name), 업종(industry), 주요고객사(main_customers)",
    inputs_opt="조사 기간, 키워드",
    outputs_fmt="Markdown 텍스트 (조사 결과 요약)",
    outputs_fields="업계동향 / 특허정보 / 공급망요건 / 위험신호",
    tools="WebSearch [Anthropic tool_use] / BaseAgent.run()",
    api="WebSearch (Claude tool_use)",
    verify_group="VerifyStrategy",
    law_ref="없음 (조사 위주)",
    perspective_4="법인(경쟁환경파악), 주주(시장가치참고), 과세관청(산업동향참고), 금융기관(시장리스크)",
    upstream="없음 (독립 실행)", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="60~120초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="PolicyFundingAgent", file="policy_funding_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="정책자금 매칭",
    single_resp="부채비율·임직원·업종 입력 → 신청 가능 정책자금·바우처·기업인증 혜택을 금리·한도와 함께 제시.",
    inputs_req="부채비율(debt_ratio), 임직원수(employees), 업종(industry)",
    inputs_opt="정책자금 이력, 기업인증 현황",
    outputs_fmt="Markdown 텍스트 (기관별 정책자금 매칭 표)",
    outputs_fields="기관 / 상품명 / 한도 / 금리 / 신청요건",
    tools="BaseAgent.run()",
    api="[보정필요: 중진공·기보·신보 API 연동 여부]",
    verify_group="VerifyStrategy",
    law_ref="중소기업기본법 / 조세특례제한법 §7 (중소기업 특별세액감면)",
    perspective_4="법인(자금조달비용절감), 주주(금융부담완화), 과세관청(지원금익금산입여부), 금융기관(대출가용성확대)",
    upstream="CreditRatingAgent (신용등급 참조)", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="CashFlowAgent", file="cash_flow_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="현금흐름 분석",
    single_resp="월 평균 매출·유동비율 입력 → 12개월 현금흐름 시뮬레이션 + 흑자도산 리스크 진단 + 운전자본 개선 방안.",
    inputs_req="월평균매출(revenue/12), 유동비율(current_ratio), 유동자산(current_assets), 유동부채(current_liabilities)",
    inputs_opt="매출 계절성, 회수기간",
    outputs_fmt="Markdown 텍스트 (12개월 CF 표 + 위험 신호)",
    outputs_fields="월별현금흐름 / 최소현금잔고 / 리스크월 / 개선방안",
    tools="BaseAgent.run()",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="[보정필요]",
    perspective_4="법인(흑자도산방지), 주주(배당가능시점), 과세관청(현금흐름이상징후), 금융기관(상환능력판단)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="CreditRatingAgent", file="credit_rating_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="신용등급 분석",
    single_resp="부채비율·유동비율·영업이익률·이자보상배율 입력 → 신용등급 추정 + 등급 상승을 통한 금리 절감 전략.",
    inputs_req="부채비율(debt_ratio), 유동비율(current_ratio), 영업이익률(operating_margin), 이자보상배율(interest_coverage)",
    inputs_opt="기존 금융기관 등급, 신용보증 이력",
    outputs_fmt="Markdown 텍스트 (등급 추정 근거 + 개선 전략)",
    outputs_fields="추정등급 / 산출근거 / 등급상승방안 / 금리절감효과",
    tools="BaseAgent.run()",
    api="[보정필요: ECOS_API 연동 여부]",
    verify_group="VerifyStrategy",
    law_ref="은행업감독업무시행세칙 (내부등급법 참고)",
    perspective_4="법인(금리절감), 주주(기업가치상승), 과세관청(없음), 금융기관(여신심사기준직접연관)",
    upstream="DataValidationAgent", downstream="PolicyFundingAgent / VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="MAValuationAgent", file="ma_valuation_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="M&A 기업가치 평가",
    single_resp="당기순이익·EBITDA·총부채 입력 → DCF·PER·EV/EBITDA 3가지 방법론으로 기업가치 산출 + 외부 매각/투자유치 적정 가치 범위 제시.",
    inputs_req="순이익(net_income), EBITDA(추정), 총부채(total_debt), 총자산(total_assets)",
    inputs_opt="비교군 PER, 업종 EV/EBITDA 배수",
    outputs_fmt="Markdown 텍스트 (3방법론 비교표 + 권장 가치 범위)",
    outputs_fields="DCF가치 / PER가치 / EV/EBITDA가치 / 최종권장범위",
    tools="BaseAgent.run()",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="상증세법 §54 (보충적평가) / 자본시장법 (공정가액 기준)",
    perspective_4="법인(매각가치극대화), 주주(투자회수), 과세관청(시가과세), 금융기관(담보가치참고)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="45~60초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="ESGRiskAgent", file="esg_risk_agent.py", group="C", step=2,
    model="claude-sonnet-4-6",
    role="ESG 리스크 평가",
    single_resp="임직원·업종·주요 고객사 입력 → E·S·G 항목별 리스크 점수 + 우선 개선 과제 + EU CBAM 대응 전략.",
    inputs_req="임직원수(employees), 업종(industry), 주요고객사(main_customers)",
    inputs_opt="에너지 사용량, 탄소 배출 현황",
    outputs_fmt="Markdown 텍스트 (E/S/G 점수표 + 개선 우선순위)",
    outputs_fields="E점수 / S점수 / G점수 / CBAM적용여부 / 우선과제",
    tools="BaseAgent.run()",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="탄소중립기본법 / EU CBAM 규정 / 중대재해처벌법",
    perspective_4="법인(ESG공시리스크), 주주(기업가치장기), 과세관청(탄소세도입대비), 금융기관(ESG대출조건)",
    upstream="없음", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  # ── GROUP D-BP (1) ───────────────────────────────────────────
  dict(
    name="BusinessPlanAgent", file="business_plan_agent.py", group="D", step=2,
    model="claude-sonnet-4-6",
    role="사업계획서 작성",
    single_resp="기업 현황 데이터 입력 → 정책자금·투자유치·인증용 사업계획서 초안 자동 작성.",
    inputs_req="company_data (전체 기업 데이터 dict)",
    inputs_opt="사업계획서 유형 (정책자금/투자유치/기업인증), 목표 수혜 기관",
    outputs_fmt="Markdown 텍스트 (사업계획서 초안)",
    outputs_fields="기업현황 / 사업목표 / 재무계획 / 기대효과",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="[보정필요: 정책자금 신청 요건 등]",
    perspective_4="법인(자금조달), 주주(기업가치제고), 과세관청(없음), 금융기관(신용보강자료)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="60~120초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  # ── GROUP E (3) ─────────────────────────────────────────────
  dict(
    name="ProvisionalPaymentAgent", file="provisional_payment_agent.py", group="E", step=1,
    model="claude-sonnet-4-6",
    role="가지급금 해소",
    single_resp="가지급금 잔액·인정이자율(4.6%) 입력 → 5가지 해소 방법별 법인+개인 합산 세부담 비교 + 최적 방법 + 월별 로드맵.",
    inputs_req="가지급금잔액(provisional_payment), 기업개요(brief)",
    inputs_opt="급여증액 가능 범위, 배당 재원",
    outputs_fmt="Markdown 텍스트 (5방법 비교표 + 로드맵)",
    outputs_fields="방법별세부담 / 추천방법 / 월별실행계획 / 필요증빙",
    tools="calc_deemed_interest() [내부 도구] / BaseAgent.run()",
    api="없음",
    verify_group="VerifyTax",
    law_ref="법인세법 시행규칙 §43 (인정이자율 4.6%) / 소득세법 §20 (상여처분 시 근로소득)",
    perspective_4="법인(익금산입방지), 주주(소득세추가부담최소화), 과세관청(인정이자정산), 금융기관(재무구조영향)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (4.6% 이자 계산 오류 0건)", kpi_time="30~45초", kpi_token="4,000~6,000",
    correction_count=1,
  ),
  dict(
    name="NomineeStockAgent", file="nominee_stock_agent.py", group="E", step=1,
    model="claude-sonnet-4-6",
    role="차명주식 해소",
    single_resp="차명주식 수량·취득연도·현재 평가액 입력 → 명의신탁 증여의제 과세위험 정량화 + 4가지 해소 방법별 세부담 비교 + 최적 해소 전략.",
    inputs_req="차명주식수(nominee_shares), 취득연도(nom_acq_year), 액면가(nom_face_val), 현평가액(net_asset_per_share)",
    inputs_opt="명의수탁자 관계, 기존 신고 여부",
    outputs_fmt="Markdown 텍스트 (방법별 세부담표 + 제척기간 분석)",
    outputs_fields="증여의제세액 / 제척기간 / 4방법비교 / 권장방법 / 과점주주취득세경고",
    tools="calc_deemed_gift_tax() [내부 도구] / BaseAgent.run()",
    api="없음",
    verify_group="VerifyTax",
    law_ref="상증세법 §45의2 (명의신탁 증여의제) / 국세기본법 §26의2 (제척기간 10/15년) / 지방세법 §7⑤",
    perspective_4="법인(주주명부정확성), 주주(형사·세무리스크), 과세관청(명의신탁적발가산세), 금융기관(과점주주취득세영향)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (제척기간 계산 오류 0건)", kpi_time="30~60초", kpi_token="4,000~7,000",
    correction_count=1,
  ),
  dict(
    name="ExecutivePayAgent", file="executive_pay_agent.py", group="E", step=1,
    model="claude-sonnet-4-6",
    role="임원보수 최적화",
    single_resp="대표이사 연봉·근속연수·퇴직금 규정 유무 입력 → 퇴직금 손금 한도 산출 + 퇴직소득세 계산 + 급여·배당·퇴직금 3가지 시나리오 비교.",
    inputs_req="대표이사연봉(ceo_salary), 근속연수(ceo_tenure), 퇴직금규정유무(retirement_pay_provision), 대표나이(ceo_age)",
    inputs_opt="3년 평균 급여 명세",
    outputs_fmt="Markdown 텍스트 (3시나리오 비교표 + 최적 믹스 추천)",
    outputs_fields="손금한도액 / 퇴직소득세 / 3시나리오세후소득 / 최적보수믹스",
    tools="calc_retirement_pay_limit() [내부 도구] / BaseAgent.run()",
    api="없음",
    verify_group="VerifyTax",
    law_ref="법인세법 시행령 §44② (3년평균×1/10×근속연수) / 소득세법 §22 (퇴직소득세) / §48 (근속연수공제)",
    perspective_4="법인(임원보수손금극대화), 주주(가처분소득극대화), 과세관청(부당행위계산부인), 금융기관(인건비비율)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (퇴직소득세 계산 오류 0건)", kpi_time="30~60초", kpi_token="4,000~6,000",
    correction_count=1,
  ),
  # ── GROUP F (5) ─────────────────────────────────────────────
  dict(
    name="GiftTaxAgent", file="gift_tax_agent.py", group="F", step=2,
    model="claude-sonnet-4-6",
    role="증여세 시뮬레이션",
    single_resp="증여 재산·수증자 관계·기존 증여 이력 입력 → 증여세 계산 + 공제 한도 + 절세 시나리오.",
    inputs_req="company_data (증여자산·수증자정보 포함)",
    inputs_opt="10년 합산 증여 이력, 혼인·출산 공제 해당 여부",
    outputs_fmt="Markdown 텍스트 (증여세 계산 + 시나리오별 비교)",
    outputs_fields="공제액 / 과세표준 / 증여세액 / 세후이전금액",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyTax",
    law_ref="상증세법 §53 (증여재산공제: 배우자6억/직계성년5천만/미성년2천만) / §53의2 (혼인·출산공제 각1억, 합산최대1억)",
    perspective_4="법인(없음), 주주(승계비용최소화), 과세관청(공제요건검증), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (증여세 계산 오류 0건)", kpi_time="30~45초", kpi_token="3,000~5,000",
    correction_count=1,
  ),
  dict(
    name="InheritanceTaxAgent", file="inheritance_tax_agent.py", group="F", step=2,
    model="claude-sonnet-4-6",
    role="상속세 시뮬레이션",
    single_resp="상속 재산·가업상속공제 요건 입력 → 상속세 계산 + 가업상속공제 적용 + 사전 증여 합산 분석.",
    inputs_req="company_data (상속재산·가업자산·업력 포함)",
    inputs_opt="사전 증여 이력, 금융재산 상속공제 해당 여부",
    outputs_fmt="Markdown 텍스트 (상속세 계산표 + 공제 최적화 방안)",
    outputs_fields="상속재산 / 공제총액 / 과세표준 / 상속세 / 가업상속공제적용여부",
    tools="BaseAgent.analyze(company_data) / _calc_inheritance_tax() [내부]",
    api="없음",
    verify_group="VerifyTax",
    law_ref="상증세법 §18의2 (가업상속공제 최대600억) / §13 (사전증여합산10년) / §18 (기초공제2억)",
    perspective_4="법인(가업연속성), 주주(상속세부담최소화), 과세관청(공제요건·사후관리), 금융기관(상속재원조달)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (상속세 계산 오류 0건)", kpi_time="30~60초", kpi_token="4,000~6,000",
    correction_count=1,
  ),
  dict(
    name="VATAgent", file="vat_agent.py", group="F", step=2,
    model="claude-sonnet-4-6",
    role="부가가치세 분석",
    single_resp="매출·매입 현황 입력 → 부가세 납부액 최적화 + 환급 전략 + 과세/면세 사업 겸업 시 비율 관리 방안.",
    inputs_req="company_data (매출·매입 포함)",
    inputs_opt="과면세 매출 비율, 접대비·복리후생비 명세",
    outputs_fmt="Markdown 텍스트 (VAT 최적화 방안)",
    outputs_fields="매입세액공제가능항목 / 환급조건 / 과면세비율관리",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyTax",
    law_ref="부가가치세법 §39 (매입세액불공제) / §48 (환급) / §30 (안분계산)",
    perspective_4="법인(VAT절감), 주주(없음), 과세관청(매입세액공제적정성), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=2,
  ),
  dict(
    name="RDTaxCreditAgent", file="rd_tax_credit_agent.py", group="F", step=2,
    model="claude-sonnet-4-6",
    role="R&D 세액공제",
    single_resp="R&D 지출·기업 규모·기술 유형 입력 → R&D 세액공제액 계산 + 신성장·국가전략기술 적용 여부 + 최적화 전략.",
    inputs_req="company_data (R&D 지출·기업규모·기술유형 포함)",
    inputs_opt="전년도 R&D 지출, 연구전담부서 인정 여부",
    outputs_fmt="Markdown 텍스트 (공제액 계산표 + 최적화)",
    outputs_fields="공제율 / 공제금액 / 이월공제잔액 / 최적화전략",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyTax",
    law_ref="조세특례제한법 §10 (R&D 세액공제) — 중소기업 최대 25%/30%/40%",
    perspective_4="법인(세액공제극대화), 주주(순이익증가), 과세관청(연구개발비인정요건), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (공제율 계산 오류 0건)", kpi_time="30~45초", kpi_token="3,000~5,000",
    correction_count=1,
  ),
  dict(
    name="InvestTaxCreditAgent", file="invest_tax_credit_agent.py", group="F", step=2,
    model="claude-sonnet-4-6",
    role="통합투자세액공제",
    single_resp="설비 투자 현황·기업 규모·기술 유형 입력 → 통합투자세액공제액 계산 + 기본공제·추가공제 + 10년 이월 전략.",
    inputs_req="company_data (설비투자액·기업규모·기술유형 포함)",
    inputs_opt="전년도 투자액, 이월공제 잔액",
    outputs_fmt="Markdown 텍스트 (공제액 계산표 + 이월 전략)",
    outputs_fields="기본공제율 / 추가공제율 / 공제금액 / 이월전략",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyTax",
    law_ref="조세특례제한법 §24 (통합투자세액공제) — 10년 이월 허용",
    perspective_4="법인(설비투자세액공제극대화), 주주(순이익증가), 과세관청(공제요건적정성), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (공제율 계산 오류 0건)", kpi_time="30~45초", kpi_token="3,000~5,000",
    correction_count=1,
  ),
  # ── GROUP G (6) ─────────────────────────────────────────────
  dict(
    name="FinancialForecastAgent", file="financial_forecast_agent.py", group="G", step=3,
    model="claude-sonnet-4-6",
    role="재무예측",
    single_resp="현재 재무 데이터 입력 → 3년 재무 예측(손익계산서·재무상태표·현금흐름표) + 시나리오별 민감도 분석.",
    inputs_req="company_data 전체",
    inputs_opt="성장률 가정, 설비투자 계획",
    outputs_fmt="Markdown 텍스트 (3년 재무 예측 표)",
    outputs_fields="예측매출 / 예측순이익 / 예측부채비율 / 민감도분석",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="[보정필요]",
    perspective_4="법인(미래재무건전성), 주주(배당전망), 과세관청(세수예측), 금융기관(대출상환능력예측)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="45~90초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="CostAnalysisAgent", file="cost_analysis_agent.py", group="G", step=3,
    model="claude-sonnet-4-6",
    role="원가 분석",
    single_resp="매출원가·판관비 입력 → 원가 구조 진단 + 절감 가능 항목 + BEP(손익분기점) 분석.",
    inputs_req="company_data (매출·원가 포함)",
    inputs_opt="제품별 원가 명세, 고정비·변동비 분류",
    outputs_fmt="Markdown 텍스트 (원가 분석표 + BEP)",
    outputs_fields="원가율 / 절감항목 / BEP / 목표원가율",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="[보정필요]",
    perspective_4="법인(원가절감손익개선), 주주(이익률제고), 과세관청(원가조작여부), 금융기관(수익성지표)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="SocialInsuranceAgent", file="social_insurance_agent.py", group="G", step=3,
    model="claude-sonnet-4-6",
    role="4대보험 최적화",
    single_resp="임직원 수·업종 입력 → 4대보험 두루누리 지원 + 보험료 절감 방안 + 사업주 부담 최적화.",
    inputs_req="임직원수(employees), 업종(industry), 연매출(revenue)",
    inputs_opt="급여 수준별 인원, 신규 채용 계획",
    outputs_fmt="Markdown 텍스트 (보험료 절감 시뮬레이션)",
    outputs_fields="현재보험료 / 절감가능액 / 두루누리해당여부 / 신청방법",
    tools="BaseAgent.analyze(company_data)",
    api="없음 (향후 고용보험EDI 연동 예정)",
    verify_group="VerifyOps",
    law_ref="고용보험법 §19 / 국민연금법 §88 / 두루누리사회보험료지원사업 운영지침",
    perspective_4="법인(보험료비용절감), 주주(없음), 과세관청(4대보험신고적정성), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="PerformancePayAgent", file="performance_pay_agent.py", group="G", step=3,
    model="claude-sonnet-4-6",
    role="성과급 설계",
    single_resp="임직원 현황·업종 입력 → 세법상 손금 인정 성과급 구조 설계 + 이익참가형 vs 목표달성형 비교.",
    inputs_req="임직원수(employees), 순이익(net_income), 업종(industry)",
    inputs_opt="임직원별 직급·연봉, 기존 성과급 규정",
    outputs_fmt="Markdown 텍스트 (성과급 구조 설계안)",
    outputs_fields="성과급유형 / 지급기준 / 손금인정여부 / 세부담비교",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyOps",
    law_ref="법인세법 §26 (인건비 손금) / 근로기준법 §43",
    perspective_4="법인(인건비손금극대화), 주주(핵심인재유지), 과세관청(성과급손금요건), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=3,
  ),
  dict(
    name="DividendPolicyAgent", file="dividend_policy_agent.py", group="G", step=3,
    model="claude-sonnet-4-6",
    role="배당정책 설계",
    single_resp="소유 구조·순이익 입력 → 금융소득 종합과세 임계점(2천만) 관리 + 지주회사 배당 수취 제외율 + 최적 배당 정책 설계.",
    inputs_req="company_data (순이익·지분구조·배당이력 포함)",
    inputs_opt="주주별 금융소득 현황, 법인 주주 여부",
    outputs_fmt="Markdown 텍스트 (배당 시나리오 비교표)",
    outputs_fields="배당가능금액 / 원천징수세율(15.4%) / 종합과세임계점 / 최적배당금액",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyTax",
    law_ref="상법 §462 (배당가능이익) / 소득세법 §14③ (금융소득2천만 초과 시 종합과세) / §129 (배당소득원천징수14%+지방세1.4%=15.4%)",
    perspective_4="법인(잉여금활용), 주주(가처분소득극대화), 과세관청(금융소득종합과세), 금융기관(재무구조영향)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="95%+ (15.4% 계산 오류 0건)", kpi_time="30~45초", kpi_token="3,000~5,000",
    correction_count=1,
  ),
  dict(
    name="RelatedPartyAgent", file="related_party_agent.py", group="G", step=3,
    model="claude-sonnet-4-6",
    role="특수관계인 거래 검증",
    single_resp="특수관계인 거래 현황 입력 → 부당행위계산 부인 리스크 정량화 + 안전항(Safe Harbor) 적용 가능성 + 시가 적정성 검토.",
    inputs_req="company_data (특수관계인 거래 현황 포함)",
    inputs_opt="거래 계약서, 시가 산정 근거",
    outputs_fmt="Markdown 텍스트 (거래 유형별 위험도표 + 개선 방안)",
    outputs_fields="거래유형 / 위험도 / 안전항적용여부 / 시가조정방안",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyTax",
    law_ref="법인세법 §52 (부당행위계산부인) / 상증세법 §35~42 / 안전항: ±5% 또는 3억 기준",
    perspective_4="법인(부당행위부인리스크), 주주(이익분여리스크), 과세관청(특수관계인거래검증), 금융기관(없음)",
    upstream="DataValidationAgent", downstream="VerifyTax → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="90%+ (±5% 안전항 계산 오류 0건)", kpi_time="30~60초", kpi_token="3,000~5,000",
    correction_count=1,
  ),
  # ── GROUP H (6) ─────────────────────────────────────────────
  dict(
    name="GlobalExpansionAgent", file="global_expansion_agent.py", group="H", step=3,
    model="claude-sonnet-4-6",
    role="해외진출 전략",
    single_resp="업종·매출·주요 고객사 입력 → 해외 진출 타당성 + 진출 국가별 세금 비교 + FTA 활용 방안.",
    inputs_req="company_data 전체",
    inputs_opt="현재 수출 비율, 진출 희망 국가",
    outputs_fmt="Markdown 텍스트 (진출 타당성 + 국가별 비교)",
    outputs_fields="진출타당성점수 / 추천국가 / 세금비교 / FTA활용방안",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="조세특례제한법 §22 (해외진출기업 세금혜택) / FTA 원산지 규정",
    perspective_4="법인(해외매출확대), 주주(기업가치상승), 과세관청(이전가격과세위험), 금융기관(해외보증가용성)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="45~90초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="DXAgent", file="dx_agent.py", group="H", step=3,
    model="claude-sonnet-4-6",
    role="디지털전환(DX) 전략",
    single_resp="업종·임직원·매출 입력 → DX 투자 우선순위 + 정부 DX 지원사업 연계 + ROI 추정.",
    inputs_req="company_data 전체",
    inputs_opt="현재 IT 인프라 수준, DX 예산",
    outputs_fmt="Markdown 텍스트 (DX 로드맵 + ROI)",
    outputs_fields="DX성숙도 / 우선투자영역 / 지원사업매칭 / ROI추정",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="중소기업 스마트제조혁신 지원사업 요건",
    perspective_4="법인(운영효율화), 주주(기업가치제고), 과세관청(없음), 금융기관(DX담보가치없음)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="45~90초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="SubcontractAgent", file="subcontract_agent.py", group="H", step=3,
    model="claude-sonnet-4-6",
    role="하도급 리스크 관리",
    single_resp="주요 고객사·업종 입력 → 하도급법 위반 리스크 진단 + 불공정 거래 조항 확인 + 하도급대금 보호 방안.",
    inputs_req="주요고객사(main_customers), 업종(industry)",
    inputs_opt="하도급 계약서, 대금 지급 현황",
    outputs_fmt="Markdown 텍스트 (위반 위험 목록 + 보호 방안)",
    outputs_fields="위반위험항목 / 위험도 / 법적제재 / 개선방안",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyOps",
    law_ref="하도급거래공정화법 §13 (하도급대금지급) / §8 (부당특약금지)",
    perspective_4="법인(하도급리스크관리), 주주(분쟁비용최소화), 과세관청(없음), 금융기관(미수채권리스크)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~45초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="IPOAgent", file="ipo_agent.py", group="H", step=3,
    model="claude-sonnet-4-6",
    role="IPO 전략",
    single_resp="재무 현황·업종 입력 → IPO 적합성 진단 + 코스닥/코넥스 요건 비교 + 상장 준비 로드맵.",
    inputs_req="company_data 전체 (매출·순이익·자기자본 중심)",
    inputs_opt="주주 구성, 우리사주조합 현황",
    outputs_fmt="Markdown 텍스트 (IPO 타당성 + 로드맵)",
    outputs_fields="IPO타당성점수 / 상장요건충족여부 / 갭분석 / 준비로드맵",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="자본시장법 §390 (코스닥 상장 요건) / §391 (코넥스 요건)",
    perspective_4="법인(자본조달), 주주(지분가치실현), 과세관청(상장차익과세), 금융기관(상장이후금융가용성)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="45~90초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="FranchiseAgent", file="franchise_agent.py", group="H", step=3,
    model="claude-sonnet-4-6",
    role="프랜차이즈 전략",
    single_resp="업종·매출 입력 → 프랜차이즈 확장 타당성 + 가맹사업법 컴플라이언스 + 세금 구조 설계.",
    inputs_req="company_data 전체",
    inputs_opt="현재 매장 수, 가맹 계약서",
    outputs_fmt="Markdown 텍스트 (타당성 진단 + 법적 구조)",
    outputs_fields="프랜차이즈타당성 / 가맹사업법위반위험 / 세금구조 / 확장로드맵",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyOps",
    law_ref="가맹사업법 §2 / §11 (정보공개서등록) / §12 (허위정보제공금지)",
    perspective_4="법인(사업확장), 주주(수익다각화), 과세관청(가맹금수익과세), 금융기관(브랜드담보가치)",
    upstream="DataValidationAgent", downstream="VerifyOps → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="30~60초", kpi_token="[보정필요]",
    correction_count=4,
  ),
  dict(
    name="DebtRestructuringAgent", file="debt_restructuring_agent.py", group="H", step=3,
    model="claude-sonnet-4-6",
    role="부채 구조조정",
    single_resp="총부채·이자율 입력 → 부채 구조조정 필요성 진단 + 채무 재조정·DES·출자전환 시나리오 + 금리 절감 방안.",
    inputs_req="총부채(total_debt), 이자비용 추정, 현금흐름",
    inputs_opt="금융기관별 대출 현황, 기존 담보 내역",
    outputs_fmt="Markdown 텍스트 (시나리오별 비교 + 권장 방안)",
    outputs_fields="현재이자부담 / 구조조정시나리오 / 금리절감효과 / 리스크",
    tools="BaseAgent.analyze(company_data)",
    api="없음",
    verify_group="VerifyStrategy",
    law_ref="채무자회생법 §119 (회사정리계획) / 기업구조조정촉진법",
    perspective_4="법인(이자비용절감), 주주(자본잠식방지), 과세관청(채무면제이익익금산입), 금융기관(채권보전)",
    upstream="DataValidationAgent", downstream="VerifyStrategy → ReportAgent",
    fix_handling="try/except 격리 → agent_errors 기록",
    kpi_acc="[보정필요]", kpi_time="45~90초", kpi_token="[보정필요]",
    correction_count=4,
  ),
]

# ──────────────────────────────────────────────────────────────
# 4자관점 분류 맵 (agent name → 주 관점)
# ──────────────────────────────────────────────────────────────
PERSPECTIVE_MAP = {
  "TaxAgent": "법인", "StockAgent": "법인+주주", "SuccessionAgent": "주주",
  "FinanceAgent": "법인", "LegalAgent": "법인", "PatentAgent": "법인",
  "LaborAgent": "법인", "RealEstateAgent": "주주", "InsuranceAgent": "주주",
  "IndustryAgent": "과세관청", "WebResearchAgent": "법인", "PolicyFundingAgent": "금융기관",
  "CashFlowAgent": "법인", "CreditRatingAgent": "금융기관", "MAValuationAgent": "주주",
  "ESGRiskAgent": "법인", "BusinessPlanAgent": "법인",
  "ProvisionalPaymentAgent": "법인", "NomineeStockAgent": "법인+주주", "ExecutivePayAgent": "주주",
  "GiftTaxAgent": "주주", "InheritanceTaxAgent": "주주", "VATAgent": "법인",
  "RDTaxCreditAgent": "법인", "InvestTaxCreditAgent": "법인",
  "FinancialForecastAgent": "법인", "CostAnalysisAgent": "법인",
  "SocialInsuranceAgent": "법인", "PerformancePayAgent": "법인",
  "DividendPolicyAgent": "주주", "RelatedPartyAgent": "과세관청",
  "GlobalExpansionAgent": "법인", "DXAgent": "법인", "SubcontractAgent": "법인",
  "IPOAgent": "주주", "FranchiseAgent": "법인", "DebtRestructuringAgent": "금융기관",
}


# ──────────────────────────────────────────────────────────────
# 명세서 생성 함수
# ──────────────────────────────────────────────────────────────
SPEC_TEMPLATE = """\
---
name: {name}
type: agent_spec
status: active
group: {group}
step: {step}
model: {model}
source_file: agents/{file}
4자관점: {perspective}
---

# {name} — 표준 명세서 (SPEC)

## 1. 단일책임
{single_resp}

## 2. 입력

**필수**: {inputs_req}

**선택**: {inputs_opt}

## 3. 출력

**형식**: {outputs_fmt}

**필수 필드**: {outputs_fields}

## 4. 사용 도구

| 항목 | 내용 |
|---|---|
| 스킬·도구 | {tools} |
| 외부 API | {api} |
| 모델 | {model} |

## 5. 자가검증 3축

① **계산 정확성**: {law_ref}

② **법령·통계 근거**: 적용 법령 — {law_ref}

③ **4자관점 교차 분석**:
{perspective_4}

## 6. 협력 에이전트

| 방향 | 에이전트 |
|---|---|
| 상류 | {upstream} |
| 하류 | {downstream} |

## 7. 실패 처리

{fix_handling}

## 8. KPI

| 지표 | 목표 |
|---|---|
| 정확도 | {kpi_acc} |
| 응답시간 | {kpi_time} |
| 평균 토큰 | {kpi_token} |

---
*보정 필요 항목: {correction_count}개 — D+18~19 사용자 검토 필요*
"""


def main():
    created = 0
    for a in AGENTS:
        perspective = PERSPECTIVE_MAP.get(a["name"], "[보정필요]")
        content = SPEC_TEMPLATE.format(
            name=a["name"], file=a["file"], group=a["group"], step=a["step"],
            model=a["model"], perspective=perspective,
            single_resp=a["single_resp"],
            inputs_req=a["inputs_req"], inputs_opt=a["inputs_opt"],
            outputs_fmt=a["outputs_fmt"], outputs_fields=a["outputs_fields"],
            tools=a["tools"], api=a["api"],
            law_ref=a["law_ref"], perspective_4=a["perspective_4"],
            upstream=a["upstream"], downstream=a["downstream"],
            fix_handling=a["fix_handling"],
            kpi_acc=a["kpi_acc"], kpi_time=a["kpi_time"], kpi_token=a["kpi_token"],
            correction_count=a["correction_count"],
        )
        fname = os.path.join(OUT, f"{a['name']}_SPEC.md")
        with open(fname, "w", encoding="utf-8") as f:
            f.write(content)
        created += 1
        print(f"  OK {a['name']}_SPEC.md  [GROUP {a['group']} | correction={a['correction_count']}]")

    print(f"\nTotal {created} SPEC files created -> {OUT}")


if __name__ == "__main__":
    main()
